---

- name: check if rules file exists
  stat:
    path: /var/lib/icinga2/certs/ticket
  register: icinga2_client_register_ticket_generated

- name: get ticket from master (direct)
  uri:
    url: '{{ icinga2_client_api_url }}/v1/actions/generate-ticket'
    method: POST
    user: '{{ icinga2_client_api_user }}'
    password: '{{ icinga2_client_api_pass }}'
    body: '{ "cn": "{{ inventory_hostname }}"}'
    force_basic_auth: yes
    status_code: 200
    body_format: 'json'
    headers:
      Accept: 'application/json'
    validate_certs: no
  register: icinga2_client_register_ticket
  when: not icinga2_client_register_ticket_generated.stat.exists
  delegate_to: '{{ icinga2_client_master_reachable_host | default(omit) }}'

- name: create cert folder for icinga2
  file:
    path: /var/lib/icinga2/certs
    state: directory
    mode: 0750
    owner: '{{ icinga2_client_file_owner }}'
    group: '{{ icinga2_client_file_group }}'

# - name: ticket and fqdn
#   debug:
#     msg: "{{ icinga2_client_register_ticket.json.results.0.ticket }}: is for {{ inventory_hostname }}"

- name: get ca from icinga2 masters (direct)
  command: |
    icinga2 pki save-cert --host {{ icinga2_client_monitoring_parents[0] }} \
    --trustedcert /var/lib/icinga2/certs/icinga2_master_ca.crt
  args:
    creates: /var/lib/icinga2/certs/icinga2_master_ca.crt
  when: icinga2_client_master_reachable_host is not defined

- name: check if ca file exists
  stat:
    path: /var/lib/icinga2/certs/ca.crt
  register: icinga2_client_register_ca_created
  when: icinga2_client_master_reachable_host is defined

- name: get ca from icinga2 masters (delegate)
  command: cat /var/lib/icinga2/certs/ca.crt
  register: icinga2_client_register_ca
  when: icinga2_client_master_reachable_host is defined and not icinga2_client_register_ca_created.stat.exists
  delegate_to: '{{ icinga2_client_csr_signing_master }}'

- name: save ca from icinga2 master (delegate)
  copy:
    content: '{{ icinga2_client_register_ca["stdout"] }}'
    dest: /var/lib/icinga2/certs/ca.crt
    mode: 0644
  when: icinga2_client_master_reachable_host is defined and not icinga2_client_register_ca_created.stat.exists

- name: create new certs
  command: >
    icinga2 pki new-cert
    --cn {{ inventory_hostname }}
    --key /var/lib/icinga2/certs/{{ inventory_hostname }}.key
    --cert /var/lib/icinga2/certs/{{ inventory_hostname }}.crt
  register: icinga2_client_register_certs_created
  when: icinga2_client_master_reachable_host is defined
  args:
    creates: /var/lib/icinga2/certs/{{ inventory_hostname }}.key

- name: setup node and get certificates signed (direct)
  command: |
    icinga2 node setup \
    --zone {{ inventory_hostname }} \
    --endpoint {{ icinga2_client_monitoring_parents[0] }} \
    --parent_host {{ icinga2_client_monitoring_parents[0] }} \
    --parent_zone {{ icinga2_client_parent_zone }} \
    --ticket {{ icinga2_client_register_ticket.json.results.0.ticket }} \
    --trustedcert /var/lib/icinga2/certs/icinga2_master_ca.crt \
    --accept-config --accept-commands
  args:
    creates: /var/lib/icinga2/certs/ca.crt
  when: not icinga2_client_register_ticket_generated.stat.exists and icinga2_client_master_reachable_host is not defined

- name: setup node and get certificates signed (indirect)
  command: |
    icinga2 node setup \
    --zone {{ inventory_hostname }} \
    --endpoint {{ icinga2_client_monitoring_parents[0] }} \
    --trustedcert /var/lib/icinga2/certs/icinga2_master_ca.crt \
    --accept-config --accept-commands
  args:
    creates: /var/lib/icinga2/certs/ca.crt
  when: not icinga2_client_register_ticket_generated.stat.exists and icinga2_client_master_reachable_host is defined

- name: restart icinga2
  service:
    name: icinga2
    state: restarted

- name: get the certificate fingerprint
  shell: >
    set -o pipefail;
    openssl x509
    -in /var/lib/icinga2/certs/{{ inventory_hostname }}.crt
    -fingerprint -sha256 -noout | cut -d '=' -f 2 | sed 's/://g' | tr A-Z a-z
  register: icinga2_client_register_certfinger
  when: icinga2_client_master_reachable_host is defined and icinga2_client_register_certs_created.changed # noqa 503

- name: sign certificate request on master
  command: >
    icinga2 ca sign {{ icinga2_client_register_certfinger['stdout'] }}
  delegate_to: '{{ icinga2_client_csr_signing_master }}'
  when: icinga2_client_master_reachable_host is defined and icinga2_client_register_certs_created.changed # noqa 503
